const readline = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');

console.log('=================================');
console.log('🤖 AI Proxy Configuration Wizard');
console.log('=================================\n');

function ask(question, defaultValue) {
  return new Promise(resolve => {
    readline.question(`${question} [${defaultValue}]: `, answer => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function run() {
  const targetApi = await ask('Downstream Target API URL', 'https://api.openai.com/v1/chat/completions');
  const clientId = await ask('OAuth Client ID', '');
  const authorizeUrl = await ask('OAuth Authorize URL', 'https://auth.yourcompany.com/oauth2/authorize');
  const tokenUrl = await ask('OAuth Token URL', 'https://auth.yourcompany.com/oauth2/token');
  const redirectUri = await ask('OAuth Redirect URI (Must whitelist!)', 'http://localhost:3001/callback');

  const envContent = `
# Auto-generated by setup.js
TARGET_API_URL=${targetApi}
OAUTH_CLIENT_ID=${clientId}
OAUTH_AUTHORIZE_URL=${authorizeUrl}
OAUTH_TOKEN_URL=${tokenUrl}
OAUTH_REDIRECT_URI=${redirectUri}
`;

  fs.writeFileSync(envPath, envContent.trim(), 'utf8');
  
  console.log('\n✅ Configuration saved securely to .env!');
  console.log('👉 You can now run: npm start');
  console.log('👉 And connect your CLI via: ANTHROPIC_BASE_URL="http://localhost:3000" claude-code');
  readline.close();
}

run().catch(err => {
  console.error(err);
  readline.close();
});
